import { useEffect, useMemo, useState } from 'react'
import { Activity, BarChart3, Camera, Cpu, Gauge, Maximize2, Settings, Users, Video, Zap, Target, Search, ChevronRight, CircleUserRound, Crosshair, MoveRight, ShieldCheck } from 'lucide-react'
import { CameraFeed, Face } from './components/CameraFeed'
import { LineChart } from './components/LineChart'
import { MetricCard } from './components/MetricCard'
import { getAnalytics, getSummary, getTracks } from './api'

const nav=[['Live Monitoring',Video],['Analytics',BarChart3],['Detected Faces',Users],['Settings',Settings]] as const

type Track={track_id:number;confidence:number;status:string;x:number;y:number;w:number;h:number}

function App(){
 const [page,setPage]=useState('Live Monitoring'); const [faces,setFaces]=useState<Face[]>([]); const [fps,setFps]=useState(0); const [summary,setSummary]=useState<any>({active_faces:0,faces_detected:0,tracking_fps:0,average_confidence:0,camera:'Browser Camera',processing:'CPU'}); const [history,setHistory]=useState<number[]>([4,5,5,6,5,7,6,8,7,9,8,10,9,11]); const [selected,setSelected]=useState<number|null>(null)
 useEffect(()=>{const refresh=async()=>{try{setSummary(await getSummary());const a=await getAnalytics(); if(a.points?.length)setHistory(a.points.slice(-30).map((x:any)=>x.tracked))}catch{}};refresh();const id=setInterval(refresh,3000);return()=>clearInterval(id)},[])
 const active=faces.filter(f=>f.status==='tracking'); const avg=active.length?active.reduce((a,f)=>a+f.confidence,0)/active.length*100:summary.average_confidence||0
 const tracks:Track[]=faces.map(f=>({...f,track_id:f.track_id}))
 const selectedFace=tracks.find(t=>t.track_id===selected)||tracks[0]
 const chart=useMemo(()=>history.length?history:[0], [history])
 return <div className="app">
  <header className="topbar"><div className="brand"><div className="brand-mark"><Target size={30}/></div><div><h1>Face Tracking System</h1><div className="brand-sub">Detect <b>•</b> Track <b>•</b> Analyze</div></div></div><div className="topnav">{nav.map(([name,Icon])=><button key={name} className={page===name?'active':''} onClick={()=>setPage(name)}><Icon size={21}/>{name}</button>)}</div><div className="system-status"><span className="online-dot"/> System Online <span className="date">Oct 2, 2026&nbsp; 17:24:36</span></div></header>
  <aside className="sidebar">{nav.map(([name,Icon])=><button key={name} className={page===name?'side-active':''} onClick={()=>setPage(name)}><Icon size={20}/>{name}</button>)}<div className="camera-status"><div className="small-title">Camera Status</div><div className="cam-online"><span className="online-dot"/>Camera-01 (Browser)</div><div>Live browser stream</div><div>Realtime detection</div></div></aside>
  <main className="content">
   {page==='Live Monitoring' && <>
    <section className="main-grid"><div><CameraFeed onFaces={setFaces} onFps={setFps}/><div className="lower-grid"><div className="selected-card panel"><div className="panel-title"><span><Crosshair size={17}/> {selectedFace?`Face-${String(selectedFace.track_id).padStart(2,'0')}`:'Face —'} <em>(Selected)</em></span><button onClick={()=>setSelected(null)}>×</button></div>{selectedFace?<div className="selected-body"><div className="avatar-placeholder"><CircleUserRound size={52}/></div><div className="detail-grid"><span>Tracking ID</span><b>{String(selectedFace.track_id).padStart(2,'0')}</b><span>Confidence</span><b>{(selectedFace.confidence*100).toFixed(1)}%</b><span>Position</span><b>X {selectedFace.x} / Y {selectedFace.y}</b><span>Status</span><b className="status-pill">ACTIVE</b></div></div>:<div className="empty">Point a camera at a face to begin tracking.</div>}<div className="movement"><div><MoveRight size={22}/><span>Movement</span></div><b>Realtime centroid tracking</b></div></div><div className="panel analytics"><div className="panel-title"><span>Analytics</span></div><div className="tabs"><button className="tab-active">Faces Over Time</button><button>Tracking Confidence</button><button>Duration</button><button>Lost / Reacquired</button><button>Performance</button></div><div className="chart-head"><b>Faces Over Time</b><span><i className="legend detected"/> Detected <i className="legend tracked"/> Tracked</span></div><LineChart series={chart}/><div className="mini-stats"><div><b>{active.length}</b><span>Face Count (Current)</span></div><div><b>{avg.toFixed(1)}%</b><span>Tracking Confidence</span></div><div><b>{fps.toFixed(1)}</b><span>FPS</span></div><div><b>—</b><span>Camera Utilization</span></div></div></div></div></div>
    <div className="right-column"><div className="panel overview"><h2>System Overview</h2><div className="metrics"><MetricCard icon={Users} label="Active Faces" value={active.length} tone="green"/><MetricCard icon={Users} label="Faces Detected" value={summary.faces_detected||0} tone="blue"/><MetricCard icon={Zap} label="Tracking FPS" value={fps.toFixed(1)} tone="purple"/><MetricCard icon={Gauge} label="Avg. Confidence" value={`${avg.toFixed(1)}%`} tone="amber"/><MetricCard icon={Camera} label="Camera" value="Browser" tone="blue"/><MetricCard icon={Cpu} label="Processing" value="CPU" tone="cyan"/></div></div><div className="panel tracked-panel"><div className="panel-title"><span>Tracked Faces</span><button>View All <ChevronRight size={15}/></button></div>{tracks.length?tracks.slice(0,5).map(t=><button className="tracked-row" key={t.track_id} onClick={()=>setSelected(t.track_id)}><div className="face-avatar"><CircleUserRound size={29}/></div><div className="track-info"><b>Face-{String(t.track_id).padStart(2,'0')}</b><span>ID: {String(t.track_id).padStart(2,'0')}</span></div><div className="track-conf">{(t.confidence*100).toFixed(1)}%<small><i/> {t.status}</small></div><div className="spark">⌁⌁</div></button>):<div className="empty">No faces detected yet.</div>}</div></div></section>
   </>}
   {page==='Analytics' && <div className="page-panel panel"><h2>Analytics</h2><p>Live tracking telemetry is collected from the current browser camera session. Historical persistence is intentionally not enabled in this reference build.</p><LineChart series={chart}/></div>}
   {page==='Detected Faces' && <div className="page-panel panel"><h2>Detected Faces</h2><div className="search"><Search size={18}/><input placeholder="Search temporary track ID"/></div>{tracks.map(t=><div className="face-list" key={t.track_id}><CircleUserRound/><div><b>Face-{String(t.track_id).padStart(2,'0')}</b><span>Temporary session ID • {(t.confidence*100).toFixed(1)}% confidence</span></div><span className="status-pill">{t.status.toUpperCase()}</span></div>)}</div>}
   {page==='Settings' && <div className="page-panel panel"><h2>Settings</h2><div className="setting"><ShieldCheck/><div><b>Privacy mode</b><span>Temporary tracking IDs only; no biometric identity matching.</span></div><div className="toggle on"/></div><div className="setting"><Gauge/><div><b>Detection interval</b><span>Frontend sends a frame approximately every 120 ms.</span></div><strong>120 ms</strong></div><div className="setting"><Cpu/><div><b>Processing backend</b><span>FastAPI + OpenCV Haar cascade + centroid tracker.</span></div><strong>CPU</strong></div></div>}
  </main>
 </div>
}
export default App
